services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ticketing_system
      MYSQL_USER: ticket_user
      MYSQL_PASSWORD: ticket_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

  backend:
    build: ./incident-management-backend/ticketing-api
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ticket_user
      MYSQL_PASSWORD: ticket_password
      MYSQL_DB: ticketing_system
      MYSQL_PORT: 3306
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: